title: "Aakash Ravi"
description: "Data Analyst | Python | SQL | Machine Learning| Power BI"
theme: jekyll-theme-minimal
#logo: /images/profile.jpg
#show_downloads: false
#github:
#  is_project_page: false
